import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class RestService {
  constructor() {}

  enterprise: any[] = [
    {
      id: 1,
      name: 'Zdenka Salon & Spa',
      state: 'A',
      direction:
        'Jr. Monterrey 258, Santiago de Surco 15038 - Centro Comercial Caminos Del Inca ',
      phone: '+51 942 388 846',
      website: 'https://www.facebook.com/profile.php?id=100069770957901',
      latitude: null,
      longitude: null,
    },
  ];
  categories: any[] = [
    {
      id: 1,
      name: 'Color',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 2,
      name: 'Tratamiento',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 3,
      name: 'Peinados',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 4,
      name: 'Laceados',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 5,
      name: 'Rostro',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 6,
      name: 'Pestañas',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 7,
      name: 'Depilación con Hilo',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 8,
      name: 'Depilación con Miel',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 9,
      name: 'Manicure',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 10,
      name: 'Pedicure',
      state: 'A',
      logo: 'hair-dye.png',
    },
  ];
  servicios: any[] = [
    {
      id: 1,
      id_categoria: 1,
      name: 'Mechas balayage',
      price: 240,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 2,
      id_categoria: 1,
      name: 'Mechas tradicionales',
      price: 200,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 3,
      id_categoria: 1,
      name: 'lluminación',
      price: 180,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 4,
      id_categoria: 1,
      name: 'Shade Redken',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 5,
      id_categoria: 1,
      name: 'Tinte raíz Redken',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 6,
      id_categoria: 1,
      name: 'Tinte raíz',
      price: 90,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 7,
      id_categoria: 2,
      name: 'Intenso',
      price: 80,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 8,
      id_categoria: 2,
      name: 'Moroccanoil',
      price: 120,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 9,
      id_categoria: 2,
      name: 'Biotop',
      price: 120,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 10,
      id_categoria: 2,
      name: 'Acidic Bonding Concentrate Redken',
      price: 120,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 11,
      id_categoria: 3,
      name: 'Peinado',
      price: 80,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 12,
      id_categoria: 3,
      name: 'Moño',
      price: 100,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 13,
      id_categoria: 3,
      name: 'Corte de damas',
      price: 80,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 14,
      id_categoria: 3,
      name: 'Corte de caballero',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 15,
      id_categoria: 3,
      name: 'Cepillado',
      price: 40,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 16,
      id_categoria: 3,
      name: 'Planchado',
      price: 40,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 17,
      id_categoria: 4,
      name: 'Botox Capilar',
      price: 200,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 18,
      id_categoria: 4,
      name: 'Alisado brasilero',
      price: 300,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 19,
      id_categoria: 4,
      name: 'Laceado japonés',
      price: 350,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 20,
      id_categoria: 4,
      name: 'Photohair',
      price: 400,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 21,
      id_categoria: 5,
      name: 'Maquillaje clásico',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 22,
      id_categoria: 5,
      name: 'Maquillaje de quinceañera',
      price: 150,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 23,
      id_categoria: 5,
      name: 'Maquillaje de novia',
      price: 250,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 24,
      id_categoria: 5,
      name: 'Limpieza de cutis clásica',
      price: 100,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 25,
      id_categoria: 5,
      name: 'Limpieza profunda',
      price: 130,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 26,
      id_categoria: 5,
      name: 'Planchado de cejas',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 27,
      id_categoria: 5,
      name: 'Pigmentación de cejas',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 28,
      id_categoria: 6,
      name: '1x1',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 29,
      id_categoria: 6,
      name: 'Tira',
      price: 40,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 30,
      id_categoria: 6,
      name: 'Extensiones',
      price: 200,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 31,
      id_categoria: 6,
      name: 'Rizado permanente',
      price: 55,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 32,
      id_categoria: 6,
      name: 'Lifting',
      price: 70,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 33,
      id_categoria: 7,
      name: 'Frente',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 34,
      id_categoria: 7,
      name: 'Cejas',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 35,
      id_categoria: 7,
      name: 'Patillas',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 36,
      id_categoria: 7,
      name: 'Bozo',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 37,
      id_categoria: 7,
      name: 'Mentón',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 38,
      id_categoria: 7,
      name: 'Rostro',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 39,
      id_categoria: 8,
      name: 'Cejas',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 40,
      id_categoria: 8,
      name: 'Patillas',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 41,
      id_categoria: 8,
      name: 'Bozo',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 42,
      id_categoria: 8,
      name: 'Mentón',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 43,
      id_categoria: 8,
      name: 'Rostro',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 44,
      id_categoria: 8,
      name: 'Axila',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 45,
      id_categoria: 8,
      name: 'Brazos',
      price: 35,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 46,
      id_categoria: 8,
      name: 'Brazos 1/2',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 47,
      id_categoria: 8,
      name: 'Espalda',
      price: 55,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 48,
      id_categoria: 8,
      name: 'Espalda lumbar',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 49,
      id_categoria: 8,
      name: 'Pierna',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 50,
      id_categoria: 8,
      name: '½Pierna superior',
      price: 35,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 51,
      id_categoria: 8,
      name: '½Pierna inferior',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 52,
      id_categoria: 8,
      name: 'Abdomen',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 53,
      id_categoria: 8,
      name: 'Vientre',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 54,
      id_categoria: 8,
      name: 'Brasilera',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 55,
      id_categoria: 8,
      name: 'Bikini',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 56,
      id_categoria: 9,
      name: 'Gel',
      price: 45,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 57,
      id_categoria: 9,
      name: 'OPI',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 58,
      id_categoria: 9,
      name: 'Masglo',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 59,
      id_categoria: 9,
      name: 'Básica',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 60,
      id_categoria: 9,
      name: 'Tips',
      price: 35,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 61,
      id_categoria: 9,
      name: 'Uñas Babyboomer',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 62,
      id_categoria: 9,
      name: 'Uñas esculpidas',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 63,
      id_categoria: 9,
      name: 'Uñas acrílicas-Acrigel-Gel',
      price: 80,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 64,
      id_categoria: 9,
      name: 'Mantenimiento Uñas Acrilicas-Acrigel-Gel',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 65,
      id_categoria: 10,
      name: 'Gel',
      price: 55,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 66,
      id_categoria: 10,
      name: 'OPI',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 67,
      id_categoria: 10,
      name: 'Masglo',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 68,
      id_categoria: 10,
      name: 'Básica',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
  ];
  horarios: any[] = [
    {
      id_horario: 1,
      id_servicio: 1,
      range: '10:00',
    },
    {
      id_horario: 2,
      id_servicio: 1,
      range: '10:30',
    },
    {
      id_horario: 3,
      id_servicio: 1,
      range: '11:00',
    },
    {
      id_horario: 4,
      id_servicio: 1,
      range: '11:30',
    },
    {
      id_horario: 5,
      id_servicio: 1,
      range: '12:00',
    },
    {
      id_horario: 6,
      id_servicio: 1,
      range: '12:30',
    },
    {
      id_horario: 7,
      id_servicio: 1,
      range: '13:00',
    },
    {
      id_horario: 8,
      id_servicio: 1,
      range: '13:30',
    },
    {
      id_horario: 9,
      id_servicio: 1,
      range: '14:00',
    },
    {
      id_horario: 10,
      id_servicio: 1,
      range: '14:30',
    },
    {
      id_horario: 11,
      id_servicio: 1,
      range: '15:00',
    },
    {
      id_horario: 12,
      id_servicio: 1,
      range: '15:30',
    },
    {
      id_horario: 13,
      id_servicio: 1,
      range: '16:00',
    },
    {
      id_horario: 14,
      id_servicio: 1,
      range: '16:30',
    },
    {
      id_horario: 15,
      id_servicio: 1,
      range: '17:00',
    },
    {
      id_horario: 16,
      id_servicio: 1,
      range: '17:30',
    },
    {
      id_horario: 17,
      id_servicio: 1,
      range: '18:00',
    },
    {
      id_horario: 18,
      id_servicio: 1,
      range: '18:30',
    },
    {
      id_horario: 19,
      id_servicio: 1,
      range: '19:00',
    },
    {
      id_horario: 20,
      id_servicio: 1,
      range: '19:30',
    },
    {
      id_horario: 21,
      id_servicio: 1,
      range: '20:00',
    },
    {
      id_horario: 22,
      id_servicio: 1,
      range: '20:30',
    },
    {
      id_horario: 23,
      id_servicio: 1,
      range: '21:00',
    },
    {
      id_horario: 24,
      id_servicio: 1,
      range: '21:30',
    },
    {
      id_horario: 25,
      id_servicio: 1,
      range: '22:00',
    },
    {
      id_horario: 26,
      id_servicio: 1,
      range: '22:30',
    },
    {
      id_horario: 27,
      id_servicio: 1,
      range: '23:00',
    },
    {
      id_horario: 28,
      id_servicio: 2,
      range: '10:00',
    },
    {
      id_horario: 29,
      id_servicio: 2,
      range: '11:00',
    },
    {
      id_horario: 30,
      id_servicio: 2,
      range: '12:00',
    },
    {
      id_horario: 31,
      id_servicio: 2,
      range: '13:00',
    },
    {
      id_horario: 32,
      id_servicio: 2,
      range: '14:00',
    },
    {
      id_horario: 33,
      id_servicio: 2,
      range: '15:00',
    },
    {
      id_horario: 34,
      id_servicio: 2,
      range: '16:00',
    },
    {
      id_horario: 35,
      id_servicio: 2,
      range: '17:00',
    },
    {
      id_horario: 36,
      id_servicio: 2,
      range: '18:00',
    },
    {
      id_horario: 37,
      id_servicio: 2,
      range: '19:00',
    },
    {
      id_horario: 38,
      id_servicio: 2,
      range: '20:00',
    },
    {
      id_horario: 39,
      id_servicio: 2,
      range: '21:00',
    },
    {
      id_horario: 40,
      id_servicio: 2,
      range: '22:00',
    },
  ];

  getPopularServices(): any[] {
    return this.servicios.filter((service) => {
      return service.is_popular == 'S';
    });
  }

  getCategories() {
    return this.categories;
  }

  getServices() {
    return this.servicios;
  }
}
