import { Injectable } from '@angular/core';
import { LoadingController } from '@ionic/angular';

@Injectable({
  providedIn: 'root',
})
export class RestService {
  constructor(public _loadingCtrl: LoadingController) {
    this.setEnterpriseSelected(this.enterprises[0])
  }
  private enterpriseSelected: any;

  private enterprises: any[] = [
    {
      id: 1,
      name: 'Zdenka Salon & Spa',
      state: 'A',
      address:
        'Jr. Monterrey 258, Santiago de Surco 15038 - Centro Comercial Caminos Del Inca ',
      phone: '+51 942 388 846',
      website: 'https://www.facebook.com/profile.php?id=100069770957901',
      latitude: -12.1125924,
      longitude: -76.9911679,
      avatar: 'assets/empresas/zdenka.jpg'
    },
  ];
  private categories: any[] = [
    {
      id: 1,
      name: 'Color',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 2,
      name: 'Tratamiento',
      state: 'A',
      logo: 'beauty-treatment.png',
    },
    {
      id: 3,
      name: 'Peinados',
      state: 'A',
      logo: 'beauty.png',
    },
    {
      id: 4,
      name: 'Laceados',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 5,
      name: 'Rostro',
      state: 'A',
      logo: 'face-mask.png',
    },
    {
      id: 6,
      name: 'Pestañas',
      state: 'A',
      logo: 'eyelash-curler.png',
    },
    {
      id: 7,
      name: 'Depilación con Hilo',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 8,
      name: 'Depilación con Miel',
      state: 'A',
      logo: 'hair-dye.png',
    },
    {
      id: 9,
      name: 'Manicure',
      state: 'A',
      logo: 'nail-polish.png',
    },
    {
      id: 10,
      name: 'Pedicure',
      state: 'A',
      logo: 'hair-dye.png',
    },
  ];
  private services: any[] = [
    {
      id: 1,
      categorieId: 1,
      name: 'Mechas balayage',
      price: 240,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 2,
      categorieId: 1,
      name: 'Mechas tradicionales',
      price: 200,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 3,
      categorieId: 1,
      name: 'lluminación',
      price: 180,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 4,
      categorieId: 1,
      name: 'Shade Redken',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 5,
      categorieId: 1,
      name: 'Tinte raíz Redken',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 6,
      categorieId: 1,
      name: 'Tinte raíz',
      price: 90,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 7,
      categorieId: 2,
      name: 'Intenso',
      price: 80,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 8,
      categorieId: 2,
      name: 'Moroccanoil',
      price: 120,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 9,
      categorieId: 2,
      name: 'Biotop',
      price: 120,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 10,
      categorieId: 2,
      name: 'Acidic Bonding Concentrate Redken',
      price: 120,
      time: 60,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 11,
      categorieId: 3,
      name: 'Peinado',
      price: 80,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 12,
      categorieId: 3,
      name: 'Moño',
      price: 100,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 13,
      categorieId: 3,
      name: 'Corte de damas',
      price: 80,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 14,
      categorieId: 3,
      name: 'Corte de caballero',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 15,
      categorieId: 3,
      name: 'Cepillado',
      price: 40,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 16,
      categorieId: 3,
      name: 'Planchado',
      price: 40,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 17,
      categorieId: 4,
      name: 'Botox Capilar',
      price: 200,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 18,
      categorieId: 4,
      name: 'Alisado brasilero',
      price: 300,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 19,
      categorieId: 4,
      name: 'Laceado japonés',
      price: 350,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 20,
      categorieId: 4,
      name: 'Photohair',
      price: 400,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 21,
      categorieId: 5,
      name: 'Maquillaje clásico',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 22,
      categorieId: 5,
      name: 'Maquillaje de quinceañera',
      price: 150,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 23,
      categorieId: 5,
      name: 'Maquillaje de novia',
      price: 250,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 24,
      categorieId: 5,
      name: 'Limpieza de cutis clásica',
      price: 100,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 25,
      categorieId: 5,
      name: 'Limpieza profunda',
      price: 130,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 26,
      categorieId: 5,
      name: 'Planchado de cejas',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 27,
      categorieId: 5,
      name: 'Pigmentación de cejas',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 28,
      categorieId: 6,
      name: '1x1',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 29,
      categorieId: 6,
      name: 'Tira',
      price: 40,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 30,
      categorieId: 6,
      name: 'Extensiones',
      price: 200,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 31,
      categorieId: 6,
      name: 'Rizado permanente',
      price: 55,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 32,
      categorieId: 6,
      name: 'Lifting',
      price: 70,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 33,
      categorieId: 7,
      name: 'Frente',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 34,
      categorieId: 7,
      name: 'Cejas',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 35,
      categorieId: 7,
      name: 'Patillas',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 36,
      categorieId: 7,
      name: 'Bozo',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 37,
      categorieId: 7,
      name: 'Mentón',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 38,
      categorieId: 7,
      name: 'Rostro',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 39,
      categorieId: 8,
      name: 'Cejas',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 40,
      categorieId: 8,
      name: 'Patillas',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 41,
      categorieId: 8,
      name: 'Bozo',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 42,
      categorieId: 8,
      name: 'Mentón',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 43,
      categorieId: 8,
      name: 'Rostro',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 44,
      categorieId: 8,
      name: 'Axila',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 45,
      categorieId: 8,
      name: 'Brazos',
      price: 35,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 46,
      categorieId: 8,
      name: 'Brazos 1/2',
      price: 25,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 47,
      categorieId: 8,
      name: 'Espalda',
      price: 55,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 48,
      categorieId: 8,
      name: 'Espalda lumbar',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 49,
      categorieId: 8,
      name: 'Pierna',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 50,
      categorieId: 8,
      name: '½Pierna superior',
      price: 35,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 51,
      categorieId: 8,
      name: '½Pierna inferior',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 52,
      categorieId: 8,
      name: 'Abdomen',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 53,
      categorieId: 8,
      name: 'Vientre',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 54,
      categorieId: 8,
      name: 'Brasilera',
      price: 60,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 55,
      categorieId: 8,
      name: 'Bikini',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 56,
      categorieId: 9,
      name: 'Gel',
      price: 45,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 57,
      categorieId: 9,
      name: 'OPI',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 58,
      categorieId: 9,
      name: 'Masglo',
      price: 20,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 59,
      categorieId: 9,
      name: 'Básica',
      price: 15,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 60,
      categorieId: 9,
      name: 'Tips',
      price: 35,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 61,
      categorieId: 9,
      name: 'Uñas Babyboomer',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 62,
      categorieId: 9,
      name: 'Uñas esculpidas',
      price: 120,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 63,
      categorieId: 9,
      name: 'Uñas acrílicas-Acrigel-Gel',
      price: 80,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 64,
      categorieId: 9,
      name: 'Mantenimiento Uñas Acrilicas-Acrigel-Gel',
      price: 50,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 65,
      categorieId: 10,
      name: 'Gel',
      price: 55,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 66,
      categorieId: 10,
      name: 'OPI',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 67,
      categorieId: 10,
      name: 'Masglo',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
    {
      id: 68,
      categorieId: 10,
      name: 'Básica',
      price: 30,
      time: 30,
      hour_init: '10:00',
      hour_end: '23:00',
      is_popular: 'N',
    },
  ];
  private hours: any[] = [
    {
      id_horario: 1,
      id_servicio: 1,
      range: '10:00',
    },
    {
      id_horario: 2,
      id_servicio: 1,
      range: '10:30',
    },
    {
      id_horario: 3,
      id_servicio: 1,
      range: '11:00',
    },
    {
      id_horario: 4,
      id_servicio: 1,
      range: '11:30',
    },
    {
      id_horario: 5,
      id_servicio: 1,
      range: '12:00',
    },
    {
      id_horario: 6,
      id_servicio: 1,
      range: '12:30',
    },
    {
      id_horario: 7,
      id_servicio: 1,
      range: '13:00',
    },
    {
      id_horario: 8,
      id_servicio: 1,
      range: '13:30',
    },
    {
      id_horario: 9,
      id_servicio: 1,
      range: '14:00',
    },
    {
      id_horario: 10,
      id_servicio: 1,
      range: '14:30',
    },
    {
      id_horario: 11,
      id_servicio: 1,
      range: '15:00',
    },
    {
      id_horario: 12,
      id_servicio: 1,
      range: '15:30',
    },
    {
      id_horario: 13,
      id_servicio: 1,
      range: '16:00',
    },
    {
      id_horario: 14,
      id_servicio: 1,
      range: '16:30',
    },
    {
      id_horario: 15,
      id_servicio: 1,
      range: '17:00',
    },
    {
      id_horario: 16,
      id_servicio: 1,
      range: '17:30',
    },
    {
      id_horario: 17,
      id_servicio: 1,
      range: '18:00',
    },
    {
      id_horario: 18,
      id_servicio: 1,
      range: '18:30',
    },
    {
      id_horario: 19,
      id_servicio: 1,
      range: '19:00',
    },
    {
      id_horario: 20,
      id_servicio: 1,
      range: '19:30',
    },
    {
      id_horario: 21,
      id_servicio: 1,
      range: '20:00',
    },
    {
      id_horario: 22,
      id_servicio: 1,
      range: '20:30',
    },
    {
      id_horario: 23,
      id_servicio: 1,
      range: '21:00',
    },
    {
      id_horario: 24,
      id_servicio: 1,
      range: '21:30',
    },
    {
      id_horario: 25,
      id_servicio: 1,
      range: '22:00',
    },
    {
      id_horario: 26,
      id_servicio: 1,
      range: '22:30',
    },
    {
      id_horario: 27,
      id_servicio: 1,
      range: '23:00',
    },
    {
      id_horario: 28,
      id_servicio: 2,
      range: '10:30',
    },
    {
      id_horario: 29,
      id_servicio: 2,
      range: '11:30',
    },
    {
      id_horario: 30,
      id_servicio: 2,
      range: '12:30',
    },
    {
      id_horario: 31,
      id_servicio: 2,
      range: '13:30',
    },
    {
      id_horario: 32,
      id_servicio: 2,
      range: '14:30',
    },
    {
      id_horario: 33,
      id_servicio: 2,
      range: '15:30',
    },
    {
      id_horario: 34,
      id_servicio: 2,
      range: '16:30',
    },
    {
      id_horario: 35,
      id_servicio: 2,
      range: '17:30',
    },
    {
      id_horario: 36,
      id_servicio: 2,
      range: '18:30',
    },
    {
      id_horario: 37,
      id_servicio: 2,
      range: '19:30',
    },
    {
      id_horario: 38,
      id_servicio: 2,
      range: '20:30',
    },
    {
      id_horario: 39,
      id_servicio: 2,
      range: '21:30',
    },
    {
      id_horario: 40,
      id_servicio: 2,
      range: '22:30',
    },
  ];
  private profle: any = {
    id: 1,
    name: 'Osmar',
    lastName: 'Velezmoro',
    email: 'o.velezmoro@gmail.com',
    phoneNumber: '+51 942832648',
    birthDate: 'Jul 02, 2022',
    avatar: 'https://i.pravatar.cc/300?img=69',
    password: '******'
  }
  private histories: any[] = [
    {
      id: 1,
      service: this.services[1],
      enterprise: this.enterprises[0],
      date: 'Abr 22, 2022',
      stars: 0,
    },{
      id: 2,
      service: this.services[2],
      enterprise: this.enterprises[0],
      date: 'May 02, 2022',
      stars: 4,
    },{
      id: 3,
      service: this.services[5],
      enterprise: this.enterprises[0],
      date: 'May 05, 2022',
      stars: 2,
    }
  ]
  private ongoings: any[] = [
    {
      id: 1,
      service: this.services[1],
      enterprise: this.enterprises[0],
      hour: this.hours[2],
      date: 'May 22, 2022',
      dateFilter: '22-05-2022'
    },
    {
      id: 2,
      service: this.services[10],
      enterprise: this.enterprises[0],
      hour: this.hours[6],
      date: 'May 23, 2022',
      dateFilter: '23-05-2022'
    },
    {
      id: 3,
      service: this.services[10],
      enterprise: this.enterprises[0],
      hour: this.hours[8],
      date: 'May 23, 2022',
      dateFilter: '23-05-2022'
    }
  ];

  private async presentLoading() {
    const loading = await this._loadingCtrl.create({
      cssClass: 'loading',
      message: 'Por favor espere...',
    });
    await loading.present();
    console.log('Loading dismissed!');
  }

  getTimeTable(service) {
    return this.hours.filter((value) => {
      return value.id_servicio == service.id
    });
  }

  uploadStarsHistory(history, value) {
    history.stars = value;
    return history; 
  }

  getOngoings(date) {
    return this.ongoings.filter((value) => {
      return value.dateFilter == date;
    });
  }

  getHistorial(): any[] {
    return this.histories;
  }

  getEnterprises(): any[] {
    return this.enterprises;
  }

  getEnterpriseSelected(): any {
    return this.enterpriseSelected;
  }

  setEnterpriseSelected(enterprise): any {
    this.enterpriseSelected = enterprise;
  }

  getProfile(): any {
    return this.profle;
  }

  getPopularServices(): any[] {
    return this.services.filter((service) => {
      return service.is_popular == 'S';
    });
  }

  getCategories() {
    return this.categories;
  }

  getServices() {
    return this.services;
  }
}
